/*
COPYRIGHT BENJAMIN ISHERWOOD 21/03/2014
THIS SOFTWARE IS INTENDED FOR OPEN SOURCE USE, REDISTRIBUTION
IS ENCOURAGE

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
OTHER DEALINGS IN THE SOFTWARE.
*/
#ifndef SPRITE_METHODS
#define SPRITE_METHODS

#include "SPRITE.h"
	
unsigned int sprite::getSpeed(void) const {return speed;}
unsigned int sprite::getAnimationStep(void) const {return animationStep;}

void sprite::incAnimationStep(void) {animationStep++;}
void sprite::setSpeed(unsigned int newSpeed) {speed = newSpeed;}
void sprite::setAnimationStep(unsigned int frame) {animationStep = frame;}
#endif